version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.AVD.ResourceManager/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"
  - package-ecosystem: "nuget"
    directory: "/src/SmallsOnline.AVD.ResourceManager.Lib/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    assignees:
      - "Smalls1652"