# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  push:
    paths-ignore:
      - ".github/workflows/create-zip-artifact.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/dependabot.yml"
      - ".vscode/*"
      - "azure/*"
      - "docs/*"
      - "host.json"
      - "**.md"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - ".github/workflows/create-zip-artifact.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/dependabot.yml"
      - ".vscode/*"
      - "azure/*"
      - "docs/*"
      - "host.json"
      - "**.md"
      - ".gitignore"

jobs:
  build-function:
    name: Build Azure Functions library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ 'Release' ]
    env:
      DOTNET_NOLOGO: true
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'

      - name: Run 'dotnet restore'
        run: dotnet restore
        working-directory: 'src/SmallsOnline.AVD.ResourceManager'

      - name: Run MSBuild
        run: dotnet build --configuration "${{ matrix.configuration }}"
        working-directory: 'src/SmallsOnline.AVD.ResourceManager'

      - name: Upload code coverage
        uses: codecov/codecov-action@v2